package main

const MAX_INCOMING_CONNECTIONS = 256

const TCP_MAX_BACKLOG = MAX_INCOMING_CONNECTIONS

const MAX_PACKET_SIZE = 2048

const TCP_HANDSHAKE_PLAIN_SIZE = (PUBLIC_KEY_SIZE + NONCE_SIZE)
const TCP_SERVER_HANDSHAKE_SIZE = (NONCE_SIZE + TCP_HANDSHAKE_PLAIN_SIZE + MAC_SIZE)
const TCP_CLIENT_HANDSHAKE_SIZE = (PUBLIC_KEY_SIZE + TCP_SERVER_HANDSHAKE_SIZE)
const TCP_MAX_OOB_DATA_LENGTH = 1024

const NUM_RESERVED_PORTS = 16
const NUM_CLIENT_CONNECTIONS = (256 - NUM_RESERVED_PORTS)

const TCP_PACKET_ROUTING_REQUEST = 0
const TCP_PACKET_ROUTING_RESPONSE = 1
const TCP_PACKET_CONNECTION_NOTIFICATION = 2
const TCP_PACKET_DISCONNECT_NOTIFICATION = 3
const TCP_PACKET_PING = 4
const TCP_PACKET_PONG = 5
const TCP_PACKET_OOB_SEND = 6
const TCP_PACKET_OOB_RECV = 7
const TCP_PACKET_ONION_REQUEST = 8
const TCP_PACKET_ONION_RESPONSE = 9

const ARRAY_ENTRY_SIZE = 6

/* frequency to ping connected nodes and timeout in seconds */
const TCP_PING_FREQUENCY = 30
const TCP_PING_TIMEOUT = 10
